image: alpine:latest

create-pages:
  script:
    - mkdir -p public
    - |
      find . -mindepth 1 -maxdepth 1 \
        ! -name public \
        ! -name .git \
        ! -name .gitlab-ci.yml \
        -exec cp -a {} public/ \;
    - echo '<!doctype html><html><body><h1>CommitToTheTimeline</h1></body></html>' > public/index.html

  pages: true

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'