image: alpine:latest

create-pages:
  script:
    - mkdir -p public

    - cp -r Afrikaans public/ || true
    - cp -r Albania public/ || true
    - cp -r Arabic public/ || true
    - cp -r Bosnia public/ || true
    - cp -r Bulgaria public/ || true
    - cp -r Cantonese public/ || true
    - cp -r Czech-Republic public/ || true
    - cp -r Danish public/ || true
    - cp -r Dutch public/ || true
    - cp -r English public/ || true
    - cp -r French public/ || true
    - cp -r Georgia public/ || true
    - cp -r German public/ || true
    - cp -r Greece public/ || true
    - cp -r Hebrew public/ || true
    - cp -r Hindi public/ || true
    - cp -r Iceland public/ || true
    - cp -r Indonesian public/ || true
    - cp -r Iran public/ || true
    - cp -r Italy public/ || true
    - cp -r Japan public/ || true
    - cp -r Korea public/ || true
    - cp -r Mandarin public/ || true
    - cp -r Nepal public/ || true
    - cp -r Norwegian public/ || true
    - cp -r Philippines public/ || true
    - cp -r Polish public/ || true
    - cp -r Portuguese-Brazil public/ || true
    - cp -r Romanian public/ || true
    - cp -r Russian public/ || true
    - cp -r Spanish public/ || true
    - cp -r Sweden public/ || true
    - cp -r Taiwan public/ || true
    - cp -r Thailand public/ || true
    - cp -r Turkey public/ || true
    - cp -r Ukraine public/ || true
    - cp -r Vietnam public/ || true
    - cp -r Zulu public/ || true

    - cp -r ./*.html public/ 2>/dev/null || true
    - cp -r ./*.css public/ 2>/dev/null || true
    - cp -r ./*.js public/ 2>/dev/null || true

  pages:
    publish: public

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'