image: alpine:latest

create-pages:
  script:
    - mkdir -p public
    - cp -a . public/site
    - rm -rf public/site/.git
    - rm -f public/site/.gitlab-ci.yml
    - cp public/site/index.html public/index.html

  pages: true

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'